                                                                                           /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora_final;

import java.awt.Color;

/**
 *
 * @author 20PROGB19
 */
public class frmPrincipal extends javax.swing.JFrame {

    //atributos para op con 2 valores
    private double valor1 = 0;
     private String operacion = null;
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.gray);
    }
//metodo factorial
    public int factorial(int numero){
        if (numero == 0){
            return 1;
        } else {
            return numero * factorial(numero - 1);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jColorChooser1 = new javax.swing.JColorChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnCero = new javax.swing.JButton();
        btnUno = new javax.swing.JButton();
        btnDos = new javax.swing.JButton();
        btnTres = new javax.swing.JButton();
        btnCuatro = new javax.swing.JButton();
        btnCinco = new javax.swing.JButton();
        btnSeis = new javax.swing.JButton();
        btnSiete = new javax.swing.JButton();
        btnOcho = new javax.swing.JButton();
        btnNueve = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btnPor = new javax.swing.JButton();
        btnEntre = new javax.swing.JButton();
        btnPorCiento = new javax.swing.JButton();
        btnRaizCuadrada = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnTAN = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnMasmenos = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnAutor = new javax.swing.JButton();
        btnLogNat = new javax.swing.JButton();
        btnSEN = new javax.swing.JButton();
        btnInversa = new javax.swing.JButton();
        btnXY = new javax.swing.JButton();
        btnAlCuadrado = new javax.swing.JButton();
        btnPI = new javax.swing.JButton();
        btnParentesis = new javax.swing.JButton();
        btnParentesis2 = new javax.swing.JButton();
        jrbHexadecimal = new javax.swing.JRadioButton();
        jrbOctal = new javax.swing.JRadioButton();
        jrbBinario = new javax.swing.JRadioButton();

        jButton7.setText("jButton1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResultados.setColumns(20);
        txtResultados.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        btnCero.setBackground(new java.awt.Color(153, 153, 255));
        btnCero.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnCero.setText("0");
        btnCero.setAlignmentY(0.0F);
        btnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCeroActionPerformed(evt);
            }
        });

        btnUno.setBackground(new java.awt.Color(153, 153, 255));
        btnUno.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnUno.setText("1");
        btnUno.setAlignmentY(0.0F);
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        btnDos.setBackground(new java.awt.Color(153, 153, 255));
        btnDos.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnDos.setText("2");
        btnDos.setAlignmentY(0.0F);
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnTres.setBackground(new java.awt.Color(153, 153, 255));
        btnTres.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnTres.setText("3");
        btnTres.setAlignmentY(0.0F);
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnCuatro.setBackground(new java.awt.Color(153, 153, 255));
        btnCuatro.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnCuatro.setText("4");
        btnCuatro.setAlignmentY(0.0F);
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });

        btnCinco.setBackground(new java.awt.Color(153, 153, 255));
        btnCinco.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnCinco.setText("5");
        btnCinco.setAlignmentY(0.0F);
        btnCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCincoActionPerformed(evt);
            }
        });

        btnSeis.setBackground(new java.awt.Color(153, 153, 255));
        btnSeis.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnSeis.setText("6");
        btnSeis.setAlignmentY(0.0F);
        btnSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeisActionPerformed(evt);
            }
        });

        btnSiete.setBackground(new java.awt.Color(153, 153, 255));
        btnSiete.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnSiete.setText("7");
        btnSiete.setAlignmentY(0.0F);
        btnSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSieteActionPerformed(evt);
            }
        });

        btnOcho.setBackground(new java.awt.Color(153, 153, 255));
        btnOcho.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnOcho.setText("8");
        btnOcho.setAlignmentY(0.0F);
        btnOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOchoActionPerformed(evt);
            }
        });

        btnNueve.setBackground(new java.awt.Color(153, 153, 255));
        btnNueve.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnNueve.setText("9");
        btnNueve.setAlignmentY(0.0F);
        btnNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueveActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(204, 153, 255));
        btnMenos.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setAlignmentY(0.0F);
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnMas.setBackground(new java.awt.Color(204, 153, 255));
        btnMas.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnMas.setText("+");
        btnMas.setAlignmentY(0.0F);
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnPor.setBackground(new java.awt.Color(204, 153, 255));
        btnPor.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        btnPor.setText("*");
        btnPor.setAlignmentX(0.5F);
        btnPor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorActionPerformed(evt);
            }
        });

        btnEntre.setBackground(new java.awt.Color(204, 153, 255));
        btnEntre.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnEntre.setText("/");
        btnEntre.setAlignmentY(0.0F);
        btnEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntreActionPerformed(evt);
            }
        });

        btnPorCiento.setBackground(new java.awt.Color(204, 153, 255));
        btnPorCiento.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnPorCiento.setText("%");
        btnPorCiento.setAlignmentY(0.0F);
        btnPorCiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorCientoActionPerformed(evt);
            }
        });

        btnRaizCuadrada.setBackground(new java.awt.Color(255, 204, 255));
        btnRaizCuadrada.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        btnRaizCuadrada.setText("Raíz Cuadrada");
        btnRaizCuadrada.setAlignmentY(0.0F);
        btnRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizCuadradaActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(255, 204, 255));
        btnIgual.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnIgual.setText("=");
        btnIgual.setAlignmentY(0.0F);
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnFactorial.setBackground(new java.awt.Color(255, 204, 204));
        btnFactorial.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnFactorial.setText("X!");
        btnFactorial.setAlignmentY(0.0F);
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        btnCE.setBackground(new java.awt.Color(204, 204, 255));
        btnCE.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnCE.setText("CE");
        btnCE.setAlignmentY(0.0F);
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnTAN.setBackground(new java.awt.Color(255, 204, 255));
        btnTAN.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnTAN.setText("TAN");
        btnTAN.setAlignmentY(0.0F);
        btnTAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTANActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(204, 204, 255));
        btnC.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnC.setText("C");
        btnC.setAlignmentY(0.0F);
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnPunto.setBackground(new java.awt.Color(153, 153, 255));
        btnPunto.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnPunto.setText(".");
        btnPunto.setAlignmentY(0.0F);
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnMasmenos.setBackground(new java.awt.Color(153, 153, 255));
        btnMasmenos.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnMasmenos.setText("±");
        btnMasmenos.setAlignmentY(0.0F);
        btnMasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasmenosActionPerformed(evt);
            }
        });

        btnCos.setBackground(new java.awt.Color(255, 204, 255));
        btnCos.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnCos.setText("COS");
        btnCos.setAlignmentY(0.0F);
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(255, 204, 255));
        btnLog.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnLog.setText("LOG");
        btnLog.setAlignmentY(0.0F);
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnAutor.setBackground(new java.awt.Color(204, 204, 255));
        btnAutor.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnAutor.setText("Autor");
        btnAutor.setAlignmentY(0.0F);
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });

        btnLogNat.setBackground(new java.awt.Color(255, 204, 255));
        btnLogNat.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnLogNat.setText("LN");
        btnLogNat.setAlignmentY(0.0F);
        btnLogNat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogNatActionPerformed(evt);
            }
        });

        btnSEN.setBackground(new java.awt.Color(255, 204, 255));
        btnSEN.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnSEN.setText("SEN");
        btnSEN.setAlignmentY(0.0F);
        btnSEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSENActionPerformed(evt);
            }
        });

        btnInversa.setBackground(new java.awt.Color(255, 204, 204));
        btnInversa.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnInversa.setText("1/X");
        btnInversa.setAlignmentY(0.0F);
        btnInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversaActionPerformed(evt);
            }
        });

        btnXY.setBackground(new java.awt.Color(255, 204, 204));
        btnXY.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnXY.setText("X^Y");
        btnXY.setAlignmentY(0.0F);
        btnXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXYActionPerformed(evt);
            }
        });

        btnAlCuadrado.setBackground(new java.awt.Color(255, 204, 204));
        btnAlCuadrado.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnAlCuadrado.setText("X^2");
        btnAlCuadrado.setAlignmentY(0.0F);
        btnAlCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlCuadradoActionPerformed(evt);
            }
        });

        btnPI.setBackground(new java.awt.Color(153, 153, 255));
        btnPI.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnPI.setText("π");
        btnPI.setAlignmentY(0.0F);
        btnPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIActionPerformed(evt);
            }
        });

        btnParentesis.setBackground(new java.awt.Color(255, 204, 255));
        btnParentesis.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnParentesis.setText(")");
        btnParentesis.setAlignmentY(0.0F);
        btnParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesisActionPerformed(evt);
            }
        });

        btnParentesis2.setBackground(new java.awt.Color(255, 204, 255));
        btnParentesis2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        btnParentesis2.setText("(");
        btnParentesis2.setAlignmentY(0.0F);
        btnParentesis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParentesis2ActionPerformed(evt);
            }
        });

        jrbHexadecimal.setBackground(new java.awt.Color(153, 153, 255));
        jrbHexadecimal.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jrbHexadecimal.setForeground(new java.awt.Color(255, 255, 255));
        jrbHexadecimal.setText("A Hexadecimal");
        jrbHexadecimal.setAlignmentY(0.0F);
        jrbHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbHexadecimalActionPerformed(evt);
            }
        });

        jrbOctal.setBackground(new java.awt.Color(153, 153, 255));
        jrbOctal.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jrbOctal.setForeground(new java.awt.Color(255, 255, 255));
        jrbOctal.setText("A Octal");
        jrbOctal.setAlignmentY(0.0F);
        jrbOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOctalActionPerformed(evt);
            }
        });

        jrbBinario.setBackground(new java.awt.Color(153, 153, 255));
        jrbBinario.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jrbBinario.setForeground(new java.awt.Color(255, 255, 255));
        jrbBinario.setText("A binario");
        jrbBinario.setAlignmentY(0.0F);
        jrbBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBinarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnCuatro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(btnCero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUno, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(btnCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDos, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(btnSeis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTres, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(btnSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnFactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTAN, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jrbHexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnRaizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnParentesis2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnParentesis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jrbBinario, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jrbOctal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPorCiento, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAlCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnXY, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnMasmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnInversa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSEN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnLogNat, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEntre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPorCiento, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRaizCuadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnParentesis2)
                            .addComponent(btnParentesis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXY, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInversa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSEN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogNat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMasmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jrbBinario))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTAN, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jrbHexadecimal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUno, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTres, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFactorial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jrbOctal))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCeroActionPerformed
        txtResultados.append("0");
    }//GEN-LAST:event_btnCeroActionPerformed

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        txtResultados.append("1");
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
       txtResultados.append("2");
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        txtResultados.append("3");
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
       txtResultados.append("4");
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCincoActionPerformed
      txtResultados.append("5");
    }//GEN-LAST:event_btnCincoActionPerformed

    private void btnSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeisActionPerformed
        txtResultados.append("6");
    }//GEN-LAST:event_btnSeisActionPerformed

    private void btnSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSieteActionPerformed
        txtResultados.append("7");
    }//GEN-LAST:event_btnSieteActionPerformed

    private void btnOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOchoActionPerformed
        txtResultados.append("8");
    }//GEN-LAST:event_btnOchoActionPerformed

    private void btnNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueveActionPerformed
        txtResultados.append("9");
    }//GEN-LAST:event_btnNueveActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
       valor1 = Double.parseDouble(txtResultados.getText());
        txtResultados.setText("");
        operacion = "suma"; 
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        valor1 = Double.parseDouble(txtResultados.getText());
        txtResultados.setText("");
        operacion = "resta";
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorActionPerformed
        valor1 = Double.parseDouble(txtResultados.getText());
        txtResultados.setText("");
        operacion = "multiplicacion";
    }//GEN-LAST:event_btnPorActionPerformed

    private void btnEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntreActionPerformed
        valor1 = Double.parseDouble(txtResultados.getText());
        txtResultados.setText("");
        operacion = "division";
    }//GEN-LAST:event_btnEntreActionPerformed

    private void btnPorCientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorCientoActionPerformed
        valor1 = Double.parseDouble(txtResultados.getText());
        valor1 = valor1/100;
        txtResultados.setText("");
        operacion = "porcentaje";
    }//GEN-LAST:event_btnPorCientoActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        String valor = txtResultados.getText();
        txtResultados.setText(valor.substring(0, valor.length()-1));
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
       txtResultados.setText(String.valueOf(factorial(Integer.parseInt(txtResultados.getText()))));
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        txtResultados.setText(" ");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnTANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTANActionPerformed
        txtResultados.setText(String.valueOf(Math.tan(Math.toRadians(Double.parseDouble(txtResultados.getText())))));  
    }//GEN-LAST:event_btnTANActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        double valor,log;
        valor = Double.parseDouble((txtResultados.getText()));
        log = Math.log10(valor);
        txtResultados.setText(String.valueOf(log));
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        txtResultados.setText(String.valueOf(Math.cos(Math.toRadians(Double.parseDouble(txtResultados.getText())))));
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnMasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasmenosActionPerformed
        txtResultados.setText(String.valueOf(Double.parseDouble(txtResultados.getText()) * -1));
    }//GEN-LAST:event_btnMasmenosActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        txtResultados.append(".");
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizCuadradaActionPerformed
        txtResultados.setText(String.valueOf(Math.sqrt(Double.parseDouble(txtResultados.getText()))));
    }//GEN-LAST:event_btnRaizCuadradaActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
         double valor2 = Double.parseDouble(txtResultados.getText());
        switch (operacion)
                {
            case "suma":
                txtResultados.setText(String.valueOf(valor1+valor2));
                
                break;
            case "resta":
                txtResultados.setText(String.valueOf(valor1-valor2));
                break; 
            case "multiplicacion":
                txtResultados.setText(String.valueOf(valor1*valor2));
                break; 
            case "division":
                if(valor2 == 0){
                    txtResultados.setText("Error, ¡División por cero!");
                } else {
                    txtResultados.setText(String.valueOf(valor1/valor2));
                } 
                break;
            case "porcentaje":
            txtResultados.setText(String.valueOf(valor1*valor2));
                break;
            case "potenciaXY":
                txtResultados.setText(String.valueOf(Math.pow(valor1,valor2)));
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnLogNatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogNatActionPerformed
        double valor,log;
        valor = Double.parseDouble((txtResultados.getText()));
        log = Math.log(valor);
        txtResultados.setText(String.valueOf(log));
    }//GEN-LAST:event_btnLogNatActionPerformed

    private void btnSENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSENActionPerformed
        txtResultados.setText(String.valueOf(Math.sin(Math.toRadians(Double.parseDouble(txtResultados.getText())))));
    }//GEN-LAST:event_btnSENActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        frmAutor frm = new frmAutor();
        frm.setVisible(true);
    }//GEN-LAST:event_btnAutorActionPerformed

    private void btnPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIActionPerformed
      txtResultados.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_btnPIActionPerformed

    private void btnParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesisActionPerformed
        txtResultados.append(")");
    }//GEN-LAST:event_btnParentesisActionPerformed

    private void btnParentesis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentesis2ActionPerformed
        txtResultados.append("(");
    }//GEN-LAST:event_btnParentesis2ActionPerformed

    private void btnXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXYActionPerformed
        valor1 = Double.parseDouble(txtResultados.getText());
        txtResultados.setText("");
        operacion = "potenciar";
    }//GEN-LAST:event_btnXYActionPerformed

    private void btnAlCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlCuadradoActionPerformed
    txtResultados.setText(String.valueOf(Math.pow(Double.parseDouble(txtResultados.getText()),2)));   
    }//GEN-LAST:event_btnAlCuadradoActionPerformed

    private void btnInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversaActionPerformed
        txtResultados.setText(String.valueOf(1/Double.parseDouble(txtResultados.getText())));
    }//GEN-LAST:event_btnInversaActionPerformed

    private void jrbHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbHexadecimalActionPerformed
        jrbOctal.setSelected(false);
        jrbBinario.setSelected(false);
        txtResultados.setText(Integer.toHexString(Integer.parseInt(txtResultados.getText())));
    }//GEN-LAST:event_jrbHexadecimalActionPerformed

    private void jrbOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOctalActionPerformed
        jrbHexadecimal.setSelected(false);
        jrbBinario.setSelected(false);
        txtResultados.setText(Integer.toOctalString(Integer.parseInt(txtResultados.getText())));
        
    }//GEN-LAST:event_jrbOctalActionPerformed

    private void jrbBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBinarioActionPerformed
        jrbHexadecimal.setSelected(false);
        jrbOctal.setSelected(false);
        txtResultados.setText(Integer.toBinaryString(Integer.parseInt(txtResultados.getText())));
        btnDos.setEnabled(false);
        btnTres.setEnabled(false);
        btnCuatro.setEnabled(false);
        btnCinco.setEnabled(false);
        btnSeis.setEnabled(false);
        btnSiete.setEnabled(false);
        btnNueve.setEnabled(false);    
    }//GEN-LAST:event_jrbBinarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlCuadrado;
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnCinco;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnCuatro;
    private javax.swing.JButton btnDos;
    private javax.swing.JButton btnEntre;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnInversa;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnLogNat;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMasmenos;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnNueve;
    private javax.swing.JButton btnOcho;
    private javax.swing.JButton btnPI;
    private javax.swing.JButton btnParentesis;
    private javax.swing.JButton btnParentesis2;
    private javax.swing.JButton btnPor;
    private javax.swing.JButton btnPorCiento;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRaizCuadrada;
    private javax.swing.JButton btnSEN;
    private javax.swing.JButton btnSeis;
    private javax.swing.JButton btnSiete;
    private javax.swing.JButton btnTAN;
    private javax.swing.JButton btnTres;
    private javax.swing.JButton btnUno;
    private javax.swing.JButton btnXY;
    private javax.swing.JButton jButton7;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbBinario;
    private javax.swing.JRadioButton jrbHexadecimal;
    private javax.swing.JRadioButton jrbOctal;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
